export const items = [
  {
    id: "me-sonder",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/mile10/000020710020.JPEG",
    category: "photo",
    fileType: "webp",
  },
  {
    id: "oem-pebbles",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/twoPebbles.png",
    category: "photo",
    fileType: "webp",
  },
  {
    id: "fighter",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_edit-DSC09052-2.jpg.webp",
    category: "photo",
    fileType: "webp",
  },
  {
    id: "chairs",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_edit-DSC09068.jpg.webp",
    category: "photo",
    fileType: "webp",
  },
  
  {
    id: "houses-basel",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_edit-DSC09069-3.jpg.webp",
    category: "photo",
    fileType: "webp",
  },
  {
    id: "elysium-embrace",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/elysium/030425/act-embrace-900.webm",
    category: "code",
    fileType: "webm",
    link: "/elysium/",
  },
  {
    id: "shoe",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_edit-DSC09066.jpg.webp",
    category: "photo",
    fileType: "webp",
  },
  
  {
    id: "hand",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_edit-DSC09047-2.jpg.webp",
    category: "photo",
    fileType: "webp",
  },
  {
    id: "chair",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_edit-DSC09048.jpg.webp",
    category: "photo",
    fileType: "webp",
  },
  
  {
    id: "visionProImg",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_edit-DSC07941.jpg.webp",
    category: "photo",
    fileType: "webp",
  },
  {
    id: "foam-geoform-models",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_edit-07889.jpg.webp",
    category: "3d",
    fileType: "webp",
  },
  
  {
    id: "waswaswas-zurich",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_edit-DSC09049-2.jpg.webp",
    category: "photo",
    fileType: "webp",
  },
  {
    id: "metaballs-webgl",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_webgl-metaballs-trim.mov.webm",
    category: "code",
    fileType: "webm",
  },
  {
    id: "guytouchdesigner",
    url: "https://image.mux.com/waB17xivBisJ48pkoUT3c1OCby00MZ9wIY3tEcJp5sCo/animated.gif",
    category: "motion",
    fileType: "webp",
  },
  {
    id: "lucyprada",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/lucy-2-prada.jpg",
    category: "photo",
    fileType: "webp",
  },
  {
    id: "film-lightblur",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/3-vivianaFilm008.jpg",
    category: "photo",
    fileType: "webp",
  },
  {
    id: "plane-slog2",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_plane-slog2-shortest-reordered-trim.mov.webm",
    category: "video",
    fileType: "webm",
  },
  {
    id: "refridgerator",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/refrigerator-lut_1.2.1.jpg",
    category: "photo",
    fileType: "webp",
  },
  {
    id: "perryShoppingcart",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_edited-00796-perry.jpg.webp",
    category: "photo",
    fileType: "webp",
  },
  {
    id: "romaniagrass02",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_DSC09747_romania_grass.JPG.webp",
    category: "photo",
    fileType: "webp",
  },
  {
    id: "romaniagrass01",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_DSC02981.JPG.webp",
    category: "photo",
    fileType: "webp",
  },
  
  {
    id: "isdsdsdk",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/compressed_edit-03827.jpg.webp",
    category: "photo",
    fileType: "webp",
  },
  {
    id: "wipedClean",
    url: "https://stream.mux.com/bWtOP7AxOvsonYYuecvDfLM00QVyHjZu8lIOvatm011bE.m3u8",
    category: "video",
    fileType: "webm",
  },
  {
    id: "getty-video",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_getty-scene-01-trim.webm",
    category: "video",
    fileType: "webm",
  },
  {
    id: "me-standing-instreet",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_edit-061.jpg.webp",
    category: "photo",
    fileType: "webp",
  },
  {
    id: "pfolio-computers",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_old-portfolio-home.png.webp",
    category: "code",
    fileType: "webp",
  },
  {
    id: "pmini-tabletop-sunset",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_DSC04957.JPG.webp",
    category: "photo",
    fileType: "webp",
  },
  {
    id: "tennis-running",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_edit-01410.jpg.webp",
    category: "photo",
    fileType: "webp",
  },
  {
    id: "liminal-title",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_liminalTitle.png.webp",
    category: "3d",
    fileType: "webp",
  },
  {
    id: "aphi-dj",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_aphi-linkedin-4x5-instaFrame.jpg.webp",
    category: "photo",
    fileType: "webp",
  },
  {
    id: "gradientstudies",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_gradientStudies.jpg.webp",
    category: "graphic",
    fileType: "webp",
  },
  {
    id: "suanna-standing-sanjose",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_comp_edit-highGrain-03897.jpg.webp.webp",
    category: "photo",
    fileType: "webp",
  },
  {
    id: "suanna-sanjose",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_edit-05805.jpg.webp",
    category: "photo",
    fileType: "webp",
  },
  {
    id: "expression-charcoal-minis",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_expression-charcoal-minis.jpeg.webp",
    category: "sketch",
    fileType: "webp",
  },
  {
    id: "tree-sanjose",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_edit-05879.jpg.webp",
    category: "photo",
    fileType: "webp",
  },
  {
    id: "tree-2-sanjose",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_edit-05882.jpg.webp",
    category: "photo",
    fileType: "webp",
  },
];
